#! /bin/sh
highlight=1abb9b
export LPASS_AGENT_TIMEOUT=0
export GTK_THEME=Arc-Dark

sxhkd &
#hsetroot -solid '#222222'
feh --bg-scale usr/img/charles-crop.png
conky &
dunst &
compton &
unclutter --timeout 1 --ignore-scrolling --fork
# disable trackpad
xinput --disable 12

bspc config honor_size_hints true

bspc monitor eDP1 -d I II III IV V VI VII
bspc monitor HDMI1 -d VIII IX X

bspc config top_padding		20px
bspc config border_width         5
bspc config window_gap          60

bspc config focused_border_color  "#$highlight"
bspc config presel_feedback_color  "#$highlight"
bspc config normal_border_color  "#222222"
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 1.0

#bspc config split_ratio          0.61803398875
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer state=floating
bspc rule -a mpv state=floating
bspc rule -a TeamViewer state=floating
bspc rule -a Surf state=tiled manage=on
bspc rule -a Zathura state=tiled manage=on

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#xautolock -time 16 -locker 'i3lock -fe -c 808080' & 
