#! /bin/sh
case $HOSTNAME in
  "si")
    highlight=1abb9b
    xss-lock -- i3lock -fe -c 808080 &
    conky &

    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
    #xrandr --output HDMI1 --mode 1920x1080 --same-as eDP1 --scale-from 2560x1440

    #disable trackpad
    xinput --disable 12

    bspc config top_padding 20px
    bspc config border_width 7
    bspc config window_gap 60
  ;;
  "cs")
    highlight=1abb9b
    xss-lock -- i3lock -fe -c 808080 &
    conky &

    bspc monitor LVDS-1 -d I II III IV V VI VII VIII IX X

    bspc config top_padding 14px
    bspc config border_width 7
    bspc config window_gap 10
  ;;
  "pb")
    highlight=e95e8e
    conky &
    redshift -l 45:-93 &

    bspc monitor -d I II III IV V VI VII VIII IX X
    bspc config top_padding 1px
    bspc config border_width 5
    bspc config window_gap 100
    bspc rule -a steam desktop='^2' follow=no
    bspc rule -a 'VMPK-Virtual MIDI Piano Keyboard'  desktop=^10 follow=no state=floating && vmpk &
  ;;
  "zr")
    highlight=66e0ff
    sleep 5; conky -a top_right -x -2530 -y 10 -d &
    pactl set-sink-volume 0 100%
    redshift -l 45:-93 &

    xrandr --output DP-2 --right-of DP-1
    bspc monitor DP-1 -d I II III IV V
    bspc monitor DP-2 -d VI VII VIII IX X
    bspc config top_padding 1px
    bspc config border_width 5
    bspc config window_gap 40
  ;;
esac

export GTK_THEME=Arc-Dark
export LPASS_AGENT_TIMEOUT=0
export QT_QPA_PLATFORMTHEME=gtk2
export RTV_EDITOR=vim
export XDG_CONFIG_HOME=/home/mrj/.config/
# make sure gnome-keyring unlocks on login
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY

compton &
dunst &
sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc $XDG_CONFIG_HOME/sxhkd/sxhkdrc-local &

# make sure gnome-keyring unlocks on login
unclutter --timeout 1 --ignore-scrolling --fork
xrdb -merge .Xresources 2> /dev/null &

bspc rule -a discord follow=no
bspc rule -a mplayer state=floating
bspc rule -a mpv state=floating
bspc rule -a TeamViewer state=floating
bspc rule -a surf state=tiled manage=on
bspc rule -a zathura state=tiled manage=on

bspc config honor_size_hints true
bspc config focused_border_color  "#$highlight"
bspc config presel_feedback_color  "#$highlight"
bspc config normal_border_color  "#1f1f1f"
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 1.0
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
