#! /bin/sh
#highlight=e91e63
highlight=e95e8e

sxhkd &
conky &

play-with-mpv &
bspc config honor_size_hints true

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor DisplayPort-0 -d I II III IV V
#bspc monitor DVI-D-0 -d VI VII VIII IX X

bspc config border_width         5
bspc config focused_border_color  "#$highlight"
bspc config normal_border_color  "#222222"
#bspc config focused_border_color  "#ff8000"
bspc config window_gap          40
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 1.0

bspc config top_padding		1px
#bspc config split_ratio          0.61803398875
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a chromium desktop='^1'
bspc rule -a mplayer state=floating
bspc rule -a mpv state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Surf state=tiled manage=on
